### ISSUE TITLE
Admin endpoint in unmock-server

### ISSUE THREAD

**Issue by ksaaskil** [Meeshkan/unmock-js#376]
Add new `HttpServer` in `unmock-server` for setting state. This enables use cases where the mock server is running and user wants to add new services or modify their states. This issue does not cover adding such endpoints.

**Comment by mikesol** [comment]
Here are the design proposals I heard today.
The general opinion is that the structure of the endpoint should mirror OpenAPI specs.  From there, four separate proposals emerged.  In each one, I will use https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml as the base, overriding the schema for `/pets/{id}`, retrieving the schema for `/pets` and deleting all non-200 responses from `/pets`

# POST as GET
In this model, post requests fuel the entire API.

## Posting a new schema

```json
{
  "action": "POST",
  "service": "petstore",
  "address": {
    "/pets/{id}": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema" : {
                  "properties": {
                    "name": {
                      "const" : "Fluffy
                    }
                  }
                }
              }
             }
          }
        }
      }
    }
  }
}
```

## Getting a schema

```json
{
  "action": "GET",
  "service": "petstore",
  "address": {
    "/pets": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json":  "schema"
             }
          }
        }
      }
    }
  }
}
```

## Deleting requests that are not 200

```json
{
  "action": "DELETE",
  "service": "petstore",
  "address": {
    "/pets": {
      "get": {
        "responses": "200"
      }
    }
  }
}
```

**Comment by ksaaskil** [comment]
Regarding the first suggestion, I don't think the address should be represented as JSON. The standard way to address JSON paths is the [JSONPath](https://goessner.net/articles/JsonPath/) syntax. `JSONPath` has implementations in most languages and it's designed for traversing and extracting data from JSON documents. See [this example](https://github.com/ksaaskil/jsonpath-demo) for a small demo in Python using [python-jsonpath-rw](https://github.com/kennknowles/python-jsonpath-rw).

So with `JSONPath`, the first example would be something like

```bash
POST /services/petstore
{
    "address": "paths.'/pets{id}'.get.responses.200.content.'application/json'.schema.properties",
    "content": "{\"name\": {\"const\": \"Fluffy\"}}
}
```

or, if using query parameters, in the POST request:

```bash
POST /services/petstore?path="paths.'/pets{id}'.get.responses.200.content.'application/json'.schema.properties"
{
    "name": {
        "const": "Fluffy"
    }
}
```

`JSONPath` also supports "wildcards" if one needs to update multiple values, it could get messy though.

**Comment by ksaaskil** [comment]
As for the second suggestion, I'm not sure if that's "REST" either? Are there examples of using paths like that in existing APIs? How would one document that in OpenAPI, for example?
